language: node_js

node_js:
  - '13'

dist: trusty

cache:
  directories:
    - node_module

notifications:
  email:
    on_failure: change

install:
  - cd client && npm install && cd ..
  - cd client && npm install --save-dev && cd ..
  - cd server && npm install && cd ..
  - cd server && npm install --save-dev && cd ..

script:
  - cd client && npm run docs && cd ..
  - cd client && npm run eslint && cd ..
  - cd client && npm run test -- --coverage --watchAll=false && cd ..
  - cat ./client/coverage/lcov.info | ./client/node_modules/.bin/coveralls --verbose
